server.port=8081

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/event_metastore
spring.datasource.username=postgres
spring.datasource.password=passwd
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Custom properties
security.token=dev-admin-token
